- name: install samba  package opensuse
  zypper:
    name:
      - samba
    state: latest
    update_cache: yes
  when: ansible_distribution ==  "openSUSE Leap"


- name: install samba  package for  Centos
  dnf:
    name:
      - samba
    state: latest
    update_cache: yes
  when: ansible_distribution ==  "CentOS"
