- name: install unzip
  package:
    name: unzip

- name: install terraform
  unarchive:
    src: /root/ansible_tutorial/files/terraform_0.14.4_linux_amd64.zip
    dest: /usr/local/bin
    remote_src: yes
    mode: 0775
    owner: root
    group: root
